linking_esri.js - fix loader issue
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'ace/editor'
Require stack:
- /Users/lloy3317/Devtopia/ace/src/ext/linking_esri.js
- /Users/lloy3317/Devtopia/ace/Makefile.dryice.js